const stories = [
    {
        story:
            'ЦЕ ІСТОРІЯ №1!! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож',
        translation:
            '111 Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!'
    },
    {
        story:
            'ЦЕ ІСТОРІЯ №2!! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож',
        translation:
            '222 Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!'
    },
    {
        story:
            'ЦЕ ІСТОРІЯ №13! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож',
        translation:
            '333 Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!'
    },

]

export const StoryData = stories.map((value, index) => (
    {
        id: index+1,
        lesson: index+1,
        story: value.story,
        translation: value.translation,
        display: "none"
    }
))


// const StoryDataold = [
//     { id: 1, lesson: 1, story: "ЦЕ ІСТОРІЯ №1!! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож", translation: 'Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!', display: "none" },
//     { id: 2, lesson: 2, story: "А ЦЕ ВЖЕ ІСТОРІЯ №2!! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож", translation: 'Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!', display: "none" },
//     { id: 3, lesson: 3, story: "ІСТОРІЯ №3 НА ВАШОМУ ЕКРАНІ!! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож", translation: 'Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!', display: "none" },
//     { id: 4, lesson: 4, story: "ОСТАННЯ ІСТОРІЯ №4!! Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож.. Так! Але щоб дізнатися більше, нам потрібно взяти (take) цю карту та вирушити в подорож", translation: 'Liam and Emma love to explore the world. One day, they found an old map in their grandfather\’s attic. “We need to find out where this leads!” Emma said excitedly. The information on the map was faded, but it showed a big red "X" in the middle of a forest. "How much treasure do you think is buried there?" Liam asked. \n \n "Let\'s take the map and go on an adventure!" Emma said. The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else! The two of them packed their bags and set off. They didn\'t know what they would find, but they knew one thing for sure—they want an adventure over anything else!', display: "none" },
// ]

