export const ContentData = [
    "Spelling, Reading Rules",
    "Pronouns, To Be",
    "Present Simple",
    "Future Simple",
    "Past Simple",
    "Irregular Verbs",
    "Simple Tense: Negative and Interrogative Sentences",
    "Continuous Tense",
    "Continuous Tense: Negative and Interrogative Sentences",
    "Present Perfect",
    "All Tenses",
    "Prepositions of Place",
    "Time and Dates",
    "There is/there are, Articles",
    "Singular and Plural Nouns, Comparative and Superlative Adjectives",
    "Active Voice and Passive Voice",
    "Modal Verbs, Would and Used to",
    "Imperative Sentences",
    "8 basic rules of Grammar (part 1)",
    "8 basic rules of Grammar (part 2)",
    "Simple Tense Wrap Up",
    "Continues Tense Wrap Up",
    "Present Perfect Wrap Up",
    "Negative and interrogative sentences - All Tenses",
    "Irregular Verbs Continued",
    "Date and Time Wrap Up",
    "Prepositions of Place Part II",
    "Singular & Plural, Comperative & Superlative Wrap Up",
    "Active and Passive Voice Part II",
    "Future Perfect and Past Perfect",
]