const sentences = [
    //lesson 1
    { beginning: "", word: "date", translat: "[deit]", ending: "" },
    { beginning: "", word: "man", translat: "[mæn]", ending: "" },
    { beginning: "", word: "home", translat: "[houm]", ending: "" },
    { beginning: "", word: "shop", translat: "[ʃop]", ending: "" },
    { beginning: "", word: "he", translat: "[hі:]", ending: "" },
    { beginning: "", word: "pencil", translat: "[pensl]", ending: "" },
    { beginning: "", word: "student", translat: "[stjudənt]", ending: "" },
    { beginning: "", word: "cup", translat: "[kʌp]", ending: "" },
    { beginning: "", word: "time", translat: "[taim]", ending: "" },
    { beginning: "", word: "cry", translat: "[krai]", ending: "" },

    //lesson 2

    { beginning: "", word: "Я", translat: "I", ending: "love Ukraine" },
    { beginning: "", word: "Він", translat: "He", ending: "likes ice-cream" },
    { beginning: "", word: "Ми", translat: "We", ending: "learn English" },
    { beginning: "", word: "Вона", translat: "She", ending: "goes to town" },
    { beginning: "", word: "Ти", translat: "You", ending: "help people" },
    { beginning: "", word: "Вони", translat: "They", ending: "look in the window" },
    { beginning: "", word: "Ви", translat: "You", ending: "will find the key" },
    { beginning: "", word: "Воно", translat: "It", ending: "knows something" },
    { beginning: "", word: "Ми", translat: "We", ending: "want peace" },
    { beginning: "", word: "Вони", translat: "They", ending: "take our time" },
    //lesson 3
    { beginning: "I", word: "хочу", translat: "want", ending: "more juice" },
    { beginning: "She", word: "має", translat: "has", ending: "many friends" },
    { beginning: "What do you", word: "їсте", translat: "eat", ending: "?" },
    { beginning: "We", word: "говоримо", translat: "talk", ending: "about school" },
    { beginning: "All kids", word: "граються", translat: "play", ending: "" },
    { beginning: "He", word: "бігає", translat: "runs", ending: "fast" },
    { beginning: "Many birds", word: "співають", translat: "sing", ending: "" },
    { beginning: "They", word: "роблять", translat: "do", ending: "homework" },
    { beginning: "Most people", word: "посміхаються", translat: "smile", ending: "" },
    { beginning: "Time", word: "йде", translat: "goes", ending: "fast" },
    //lesson 4
    { beginning: "I", word: "прочитаю", translat: "will read", ending: "this book" },
    { beginning: "She", word: "використає", translat: "will use", ending: "that pan" },
    { beginning: "They", word: "зроблять", translat: "will make", ending: "a cake" },
    { beginning: "He", word: "залишиться", translat: "will stay", ending: "because he cares" },
    { beginning: "It", word: "буде", translat: "will be", ending: "such a fun day" },
    { beginning: "We", word: "пройдемо", translat: "will go", ending: "through the tunnel" },
    { beginning: "You", word: "отримаєш", translat: "will get", ending: "a gift" },
    { beginning: "I", word: "працюватиму", translat: "will work", ending: "tomorrow" },
    { beginning: "They", word: "допоможуть", translat: "will help", ending: "us" },
    { beginning: "This", word: "буде", translat: "will be", ending: "a different story" },
    //lesson 5
    { beginning: "I", word: "потребував", translat: "needed", ending: "help" },
    { beginning: "They", word: "дивилися", translat: "watched", ending: "a new film" },
    { beginning: "She just", word: "прибув", translat: "arrived", ending: "" },
    { beginning: "He only", word: "посміхнувся", translat: "smiled", ending: "" },
    { beginning: "We", word: "користувалися", translat: "used", ending: "the old book" },
    { beginning: "It", word: "виглядало", translat: "looked", ending: "good" },
    { beginning: "She", word: "поливала", translat: "watered", ending: "the plants" },
    { beginning: "They", word: "вивчали", translat: "studied", ending: "history" },
    { beginning: "He", word: "хотів", translat: "wanted", ending: "some water" },
    { beginning: "I", word: "дзвонив", translat: "called", ending: ", but no one answered" },
    //lesson 6    
    { beginning: "I", word: "дивився", translat: "saw", ending: "a new film" },
    { beginning: "She just", word: "пішла", translat: "went", ending: "home" },
    { beginning: "He only", word: "дала", translat: "gave", ending: "one answer" },
    { beginning: "We", word: "випили", translat: "drank", ending: "water" },
    { beginning: "They", word: "були", translat: "were", ending: "very happy" },
    { beginning: "I", word: "мали", translat: "had", ending: "a good time" },
    { beginning: "He", word: "прийшов", translat: "came", ending: "early" },
    { beginning: "She", word: "взяла", translat: "took", ending: "some bread" },
    { beginning: "I", word: "думав", translat: "thought", ending: "about that" },
    { beginning: "They", word: "склали", translat: "made", ending: "a plan" },
    //lesson 7
    { beginning: "I", word: "знаю", translat: "know", ending: "the way" },
    { beginning: "She", word: "почуватиметься", translat: "will feel", ending: "well" },
    { beginning: "He", word: "пішов", translat: "went", ending: "first" },
    { beginning: "My friend", word: "може", translat: "can", ending: "draw" },
    { beginning: "You", word: "знатимеш", translat: "will know", ending: "his name" },
    { beginning: "I", word: "сказав", translat: "said", ending: "yes" },
    { beginning: "He", word: "буде мати", translat: "will have", ending: "money" },
    { beginning: "Then we", word: "пішли", translat: "walked", ending: "home" },
    { beginning: "Each child", word: "може", translat: "can", ending: "read" },
    { beginning: "They", word: "любили", translat: "loved", ending: "art" },
    //lesson 8
    { beginning: "She", word: "дивиться", translat: "is looking", ending: "at the wall" },
    { beginning: "People", word: "подорожують", translat: "are travelling", ending: "around the world" },
    { beginning: "He", word: "читає", translat: "is reading", ending: "a newspaper" },
    { beginning: "We", word: "вивчають", translat: "are studing", ending: "the map now" },
    { beginning: "They", word: "намагаються", translat: "are trying", ending: "to find the answer" },
    { beginning: "I", word: "не їм", translat: "am not eating", ending: "much today" },
    { beginning: "She", word: "знімає", translat: "is taking", ending: "a photo" },
    { beginning: "He", word: "каже", translat: "is saying", ending: "he wants more food" },
    { beginning: "We", word: "говоримо", translat: "are talking", ending: "about something important" },
    { beginning: "My family", word: "обідає", translat: "is having", ending: "dinner" },
    //lesson 9
    {beginning: "She", word: "читає", translat: "is reading", ending: "a new book"},
    {beginning: "They", word: "не тримали", translat: "were not keeping", ending: "the door open"},
    {beginning: "We", word: "приєднаємося", translat: "will be joining", ending: "this project"},
    {beginning: "He", word: "починає", translat: "is starting", ending: "a new job"},
    {beginning: "I", word: "вивчав", translat: "was learning", ending: "a lot last year"},
    {beginning: "The teacher", word: "допомагатиме", translat: "will be helping", ending: "every student"},
    {beginning: "They", word: "працюють", translat: "are working", ending: "in the field now"},
    {beginning: "We", word: "будемо будувати", translat: "will be building", ending: "a large house"},
    {beginning: "She", word: "кликала", translat: "was calling", ending: "us"},
    {beginning: "He", word: "робив", translat: "was making", ending: "the files available"},
    //lesson 10
    {beginning: "I", word: "прожив", translat: "have lived", ending: "here for 10 years"},
    {beginning: "We both", word: "працювали", translat: "have worked", ending: "here since Summer"},
    {beginning: "They", word: "віддали", translat: "have given", ending: "us the keys"},
    {beginning: "Scientists", word: "вивчали", translat: "have studied", ending: "human behaviour for centuries"},
    {beginning: "Both teams", word: "відіграли", translat: "have played", ending: "well"},
    {beginning: "She", word: "шукала", translat: "has searched", ending: "for it since last week"},
    {beginning: "We", word: "прожили", translat: "have lived", ending: "without the car for a month"},
    {beginning: "She", word: "знайшла", translat: "has found", ending: "something interesting"},
    {beginning: "They", word: "прийшли", translat: "have come", ending: "to visit us"},
    {beginning: "We", word: "зустріли", translat: "have met", ending: "the local guide"},
    
]


export const ReplaceitExerciseData = sentences.map((value, index) => (
    {
        id: index + 1,
        lesson: Math.floor(index / 10) + 1,
        display_word: "block",
        display_translat: "none",
        sentence: {
            beginning: value.beginning,
            word: value.word,
            translat: value.translat,
            ending: value.ending
        }
    }
))
